### ISSUE TITLE
[bug] mag-eg-el definitition

### ISSUE THREAD

**Issue by hellboy81** [adjohnson916/magnificent.js#43]
where can I find mag-eg-el class definition????????????????????????????????????????????????????????????????????????????????????????????

**Comment by hellboy81** [comment]
why your class definition is [by 3rd party gh project to find](https://github.com/KhrystynaShekhovtsova/UIcourse_Project/blob/7996dac1b5d64eefc0a7df5fe0f0c23adb80add8/magnificent.js/magnificent.js-master/examples/demo/index.css#L19)????????

Is this definition deprecated??????

**Comment by adjohnson916** [comment]
@hellboy81  I believe that class was just for the example page, and it wasn't needed anymore, as as the styles were moved to `mag.css` in https://github.com/adjohnson916/magnificent.js/commit/d743f202beac9087bc0d305f762bc021e2803082. I guess I left the classes in the example HTML anyway.

Looks like the KhrystynaShekhovtsova/UIcourse_Project project has embedded an older version of magnificent in their code, that's why it appears there still.

Are you noticing a bug due to this?
